name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_PATH: OobaboogaChatUI/OobaboogaChatUI.csproj
  permissions: write-all

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Publish project
        run: dotnet publish ${{ env.PROJECT_PATH }} --self-contained -c Deploy -r win-x64 -p:PublishSingleFile=true

      - name: Compress artifacts
        run: |
          cd OobaboogaChatUI/bin/Deploy/net6.0-windows/win-x64/publish/
          7z a -r ../../../../release.zip *

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.run_number }}
          release_name: Release 1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: OobaboogaChatUI/bin/release.zip
          release-url: ${{ steps.create_release.outputs.upload_url }}
