name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_PATH: OobaboogaChatUI/OobaboogaChatUI.csproj
  permissions: write-all
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - uses: microsoft/setup-msbuild@v1.0.2

      - run: dotnet restore ${{ env.PROJECT_PATH }}

      - run: dotnet publish ${{ env.PROJECT_PATH }} --self-contained -c Deploy -r win-x64 -p:PublishSingleFile=true

      - run: |
          cd OobaboogaChatUI/bin/Deploy/net6.0-windows/win-x64/publish/
          7z a -r ../../../../release.zip *

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: OobaboogaChatUI/bin/release.zip

      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: OobaboogaChatUI/bin/release.zip
          release-url: ${{ steps.create_release.outputs.upload_url }}
          